export { default as TorrentInfoCompleted } from './torrent-info-completed.vue'
export { default as TorrentInfoDownloading } from './torrent-info-downloading.vue'
export { default as TorrentInfoError } from './torrent-info-error.vue'
export { default as TorrentInfoOther } from './torrent-info-other.vue'
export { default as TorrentInfoPaused } from './torrent-info-paused.vue'
